fix(analyzers/diagnostics): handle invalid fields in TOML
deepsourcelabs/cli pull request #183
Opened 2022-07-25 15:33 UTC by burntcarrot

Adds a couple of fixes for handling TOML validation errors - including handling invalid/extra fields present in TOML files.

2022-07-26 07:49 UTC, siddhant-deepsource requested changes
Looks good. Please address the comments. Thanks!

2022-07-26 07:49 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +// codeframeFieldRegexp is a regular expression used for matching a TOML field present in the codeframe generated by go-toml.
```suggestion
// codeframeFieldRegexp is a regular expression used for matching a TOML field present in the codeframe generated by go-toml's DecodeError.
// Ref: https://pkg.go.dev/github.com/pelletier/go-toml/v2#DecodeError
```

2022-07-26 07:49 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +	}
Please move this to a separate function.

2022-07-26 07:49 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
>  	// Get the DecodeError exported by go-toml
Please move this `DecodeError` handler to a separate function as well.

2022-07-26 07:49 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +func parseCodeframe(codeframe string) []string {
Please rename this function to something like `parseTOMLErrorCodeFrame` in order to give a context as to parsing a code frame reported as an error by the toml library.

2022-07-26 09:39 UTC, burntcarrot commented on analyzers/diagnostics/diagnostics.go
> +	// Sometimes validation errors have a blank field name. In that case, checkField should return false.
If the field is empty in the validation error itself, `checkField` returns false, which causes the diagnostic to not get printed on the console.

I couldn't find a case where blank field names have been reported, but I've added it as a check in order to ensure that it doesn't break abruptly.

2022-07-26 10:15 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +// handleDecodeErr extracts data about the decoding failure and returns a validation failure response.
```suggestion
// handleDecodeErr extracts the required data from the decoding errors of the TOML of type other than DecodeError and StrictMissingError and returns a validation failure response.
```

2022-07-26 10:15 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
>  	// Get the DecodeError exported by go-toml
```suggestion
	// Check for the DecodeError exported by go-toml.
```

2022-07-26 10:20 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +// codeframeFieldRegexp is a regular expression used for matching a TOML field present in the codeframe generated by go-toml's StrictMissingError.
```suggestion
/*
codeframeFieldRegexp is a regular expression used for matching a TOML field present in the codeframe generated by go-toml's StrictMissingError.
Ref: The example here: https://pkg.go.dev/github.com/pelletier/go-toml/v2#example-Decoder.DisallowUnknownFields
The output looks like this:
strict mode: fields in the document are missing in the target struct
2| key1 = "value1"
3| key2 = "value2"
 | ~~~~ missing field
4| key3 = "value3"
*/
```

2022-07-26 10:21 UTC, siddhant-deepsource approved these changes
Looks good to me. This improves the config validation for the user thus adding to the improved user experience. Thanks!

2022-07-26 10:23 UTC, siddhant-deepsource commented on analyzers/diagnostics/diagnostics.go
> +	// Sometimes validation errors have a blank field name. In that case, checkField should return false.
So, in this case what would the user see on running the command? Will they just see `Invalid fields found`?

2022-07-26 10:24 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +func handleStrictMissingError(err error, strictMissingError *toml.StrictMissingError, filePath string) ValidationFailure {
```suggestion
func handleStrictMissingError(strictMissingError *toml.StrictMissingError, filePath string) ValidationFailure {
```

2022-07-26 10:25 UTC, burntcarrot commented on analyzers/diagnostics/diagnostics.go
> +	// Sometimes validation errors have a blank field name. In that case, checkField should return false.
Ideally this shouldn't occur in any case, but I'll try simulating a edge case somehow locally. I'll let you know about the results.

2022-07-26 10:25 UTC, siddhant-deepsource commented on analyzers/diagnostics/diagnostics.go
> +	// Sometimes validation errors have a blank field name. In that case, checkField should return false.
Okay. Resolving for now.

2022-07-26 10:26 UTC, burntcarrot commented on analyzers/validator/utils.go
> +func handleStrictMissingError(err error, strictMissingError *toml.StrictMissingError, filePath string) ValidationFailure {
Nice catch!

2022-07-26 10:27 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +func handleStrictMissingError(err error, strictMissingError *toml.StrictMissingError, filePath string) ValidationFailure {
Thanks to the Go Analyzer! 😅

2022-07-26 10:28 UTC, siddhant-deepsource commented on analyzers/validator/utils.go
> +		validationError := handleStrictMissingError(err, strictMissingError, filePath)
```suggestion
		validationError := handleStrictMissingError(strictMissingError, filePath)
```

2022-07-26 10:31 UTC, siddhant-deepsource approved these changes

2022-07-27 19:20 UTC, siddhant-deepsource commented
@burntcarrot The tests are fixed. Please take a look and do a manual sanity test on your end in order to ensure diagnostics work on the edge cases that we have addressed in this PR. Once done, this is good to go. Thanks!

2022-07-28 02:46 UTC, burntcarrot commented
@siddhant-deepsource Did the checks on my end. Works for every test case.

2022-07-28 04:57 UTC, merged