Add logic for key validation in report subcommand
deepsourcelabs/cli pull request #201
Opened 2023-02-27 10:17 UTC by subham-deepsource

2023-02-28 06:43 UTC, subham-deepsource commented
To make the tests pass, I think we have to update the DSN. @siddhant-deepsource Right?

2023-02-28 08:14 UTC, siddhant-deepsource commented
Its the issue with using the test coverage github action. Ref: https://discuss.deepsource.io/t/breaking-deepsource-test-coverage-github-action/507

2023-03-01 09:17 UTC, anto-deepsource requested changes

2023-03-01 09:17 UTC, anto-deepsource commented on command/report/report.go
> +	cmd.Flags().StringVar(&opts.Analyzer, "analyzer", "", "name of the analyzer (example: test-coverage)")
The descriptions for `analyzer` and `key` are confusing, users might confuse `analyzer` as the language for which they are uploading the artifact. IMO, we can be more descriptive.

I'll think about and suggest something but in the meantime, if you get a better description, you can update it.

2023-03-01 11:55 UTC, tushar-deepsource commented on command/report/report.go
> +	cmd.Flags().StringVar(&opts.Analyzer, "analyzer", "", "name of the analyzer (example: test-coverage)")
```suggestion
	cmd.Flags().StringVar(&opts.Analyzer, "analyzer", "", "name of the analyzer to report the artifact to (example: test-coverage)")
```

2023-03-01 11:56 UTC, tushar-deepsource commented on command/report/report.go
> +	cmd.Flags().StringVar(&opts.ValueFile, "value-file", "", "path of the artifact value file")
```suggestion
	cmd.Flags().StringVar(&opts.ValueFile, "value-file", "", "path to the artifact value file")
```

2023-03-01 11:56 UTC, tushar-deepsource commented
CI is fixed now.

2023-03-02 08:40 UTC, tushar-deepsource commented on command/report/report.go
> +	cmd.Flags().StringVar(&opts.Key, "key", "", "shortcode of the analyzer (example: go)")
```suggestion
	cmd.Flags().StringVar(&opts.Key, "key", "", "shortcode of the language (example: go)")
```

2023-03-02 08:42 UTC, anto-deepsource submitted a review, later dismissed

2023-03-02 09:01 UTC, sourya-deepsource requested changes

2023-03-02 09:01 UTC, sourya-deepsource commented on command/report/tests/report_workflow_test.go
> +		if eq := deep.Equal(want, got); len(eq) != 0 {
`go-cmp` is already being installed. You can use `cmp.DeepEqual`.

2023-03-02 09:01 UTC, sourya-deepsource commented on command/report/tests/report_workflow_test.go
> +			}
You can use `cmp.Diff` instead.

2023-03-03 09:05 UTC, subham-deepsource commented on command/report/report.go
> +		err = fmt.Errorf("DeepSource | Error | Invalid Key: %s", reportCommandKey)
Now it looks like:
```
DeepSource | Error | Invalid Key: abc (Supported Keys: [python javascript java csharp rust go ruby scala php cxx])
```

2023-03-03 09:06 UTC, sourya-deepsource approved these changes

2023-03-03 09:10 UTC, merged