Add Github Actions CI
deepsourcelabs/cli pull request #47
Opened 2021-04-19 15:34 UTC by siddhant-deepsource

Fixes #46 

Signed-off-by: siddhant-deepsource <siddhant@deepsource.io>

2021-04-20 07:38 UTC, sourya-deepsource requested changes

2021-04-20 07:38 UTC, sourya-deepsource commented on .github/workflows/CI.yml
> +        run: 'echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa'
What's the SSH key for?

2021-04-20 07:39 UTC, siddhant-deepsource commented on .github/workflows/CI.yml
> +        run: 'echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa'
Cloning `july` repo for testing

2021-04-28 06:57 UTC, sourya-deepsource commented on .github/workflows/CI.yml
> +        run: 'echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa'
It is not a private repo.

2021-04-30 14:14 UTC, siddhant-deepsource commented on .github/workflows/CI.yml
> +        run: 'echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa'
Done

2021-05-03 09:35 UTC, sourya-deepsource approved these changes

2021-05-03 11:12 UTC, siddhant-deepsource commented
@sourya-deepsource Will there also be any changes in the cli installation script since the path [here](https://github.com/deepsourcelabs/cli/pull/47/files#diff-f2204989446cadb6e460ae9f44678be54ae8cb68c579ea4968e1bdc5845d60f9R96) has been changed to fetch the codepath from an environment variable.

2021-05-04 22:29 UTC, merged