feat: DeepSource independent SDK package
deepsourcelabs/cli pull request #66
Opened 2021-07-30 10:29 UTC by siddhant-deepsource

2021-08-17 09:51 UTC, sourya-deepsource requested changes

2021-08-17 09:51 UTC, sourya-deepsource commented on command/config/validate/validate.go
> +	AnalyzerNames      []string
This is repeated. Can it be in the config pkg?

2021-08-17 09:51 UTC, sourya-deepsource commented on command/issues/list/list.go
> +	if opts.LimitArg > 100 {
Hardcoded here. Make it a const.

2021-08-17 09:51 UTC, sourya-deepsource commented on command/issues/list/list.go
> +	deepsource := deepsource.New()
Use dependency injection here.

2021-08-17 09:51 UTC, sourya-deepsource commented on command/issues/list/list.go
> +	ctx := context.Background()
Move this a level up?

2021-08-17 09:51 UTC, sourya-deepsource commented on command/issues/list/list.go
> +		opts.showIssues(true)
```suggestion
		opts.showIssues(true)
		return nil
```

2021-08-17 09:51 UTC, sourya-deepsource commented on command/issues/list/list.go
> +		// Case 2 : Fetch list of issues for the whole project
Remove else.

2021-08-17 09:51 UTC, sourya-deepsource commented on command/issues/list/list.go
> +		opts.ptermTable[index] = issueList
```suggestion
		opts.ptermTable[index] = []string{issueLocation, analyzerShortcode, issueCode, issueTitle}
```

2021-08-17 09:51 UTC, sourya-deepsource commented on command/repo/status/status.go
> +// NewCmdVersion returns the current version of cli being used
```suggestion
// NewCmdRepoStatus returns the current version of cli being used
```

2021-08-17 09:51 UTC, sourya-deepsource commented on command/repo/status/status.go
> +		if len(remotesData) == 1 {
Could we move this to utils?

2021-08-17 09:51 UTC, sourya-deepsource commented on command/repo/view/view.go
> +	switch opts.VCSProvider {
Could be a map?

2021-08-17 09:51 UTC, sourya-deepsource commented on command/repo/view/view.go
> +	dashboardURL := fmt.Sprintf("https://deepsource.io/%s/%s/%s/", vcs, opts.Owner, opts.RepoName)
Hardcoded URL. Will be an issue with on-prem.

2021-08-17 09:51 UTC, sourya-deepsource commented on command/repo/view/view.go
> +	err = browser.OpenURL(dashboardURL)
```suggestion
	return browser.OpenURL(dashboardURL)
```

2021-08-17 09:51 UTC, sourya-deepsource commented on config/config.go
> +	TokenExpiresIn        time.Time
Verify if it contains the timezone info as well.

2021-08-17 09:51 UTC, sourya-deepsource commented on deepsource/auth/mutations/refresh_creds.go
> +	auth.RefreshAuthResponse
Revisit this.

2021-08-17 09:51 UTC, sourya-deepsource commented on deepsource/client.go
> +const host = "https://api.deepsource.io/graphql/"
Read from config?

2021-08-17 09:51 UTC, sourya-deepsource commented on deepsource/issues/queries/list_issues.go
> +	req.Header.Add("Authorization", tokenHeader)
This can be done in a single place?

2021-08-18 19:29 UTC, siddhant-deepsource commented on command/config/generate/analyzers_input.go
>  		// TODO: Remove this hard coding
The `required` field is missing from the `meta_schema` of Go and Java analyzers. Both have only `optional_required` field. Should I input the `optional_required` fields instead?

2021-08-20 08:50 UTC, siddhant-deepsource commented on command/config/generate/analyzers_input.go
>  		// TODO: Remove this hard coding
Will address this in a separate PR.

2021-08-20 09:13 UTC, vishnu-deepsource approved these changes

2021-08-20 09:15 UTC, siddhant-deepsource commented on global/global.go
> +)
Had added this package earlier. Deleted in further commits to use the `config` package itself.

2021-08-20 09:16 UTC, merged